### ISSUE TITLE
Can not select a Counter i created.

### ISSUE THREAD

**Issue by Snulian** [pirak/firebot-gambling-script#154]
**Important Information**
* Script Version: v1.0.0
* Firebot Version: 5.50.3

**Describe the bug**
When i want to use the Custom Gambling Effect on the Command i need to select a Counter, I created one but it does not show up. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Command u created for the gambling game.
2. Click on edit and then you need to go to the Fallback Subcommand, scroll down and select Add Effect.
3. Add the Custom Gambling Effect and then u need to select the Counter.
4. In my case i could not select one, i dont know if this does reproduce by others tho.

**Expected behaviour**
That i can select the Counter but its not showing.

Here a Screenshot of the "Error" i got.
![InkedUnbenannt_LI](https://user-images.githubusercontent.com/99464102/153543972-d5ec5582-f27f-44be-bc7d-7d2ebdec901c.jpg)

**Comment by pirak** [comment]
Thanks a lot for the nice and detailed bug report. I was able to reproduce the issue and [released an updated version 1.0.1](https://github.com/pirak/firebot-gambling-script/releases) with a fix for it.
