### ISSUE TITLE
"%" / how can it be added to the command?

### ISSUE THREAD

**Issue by DickerSauerlaender** [pirak/firebot-gambling-script#451]
"all" is working well now after deleting and adding. How can i also add the possibility with %?

**Comment by pirak** [comment]
Are you talking about the percentage as described in https://github.com/pirak/firebot-gambling-script#usage?
For me all three versions work, so I’m not sure how I can reproduce the issue to help you in this case.

(Firebot 5.57.0, newly setup effect, existing command)


```
me: !gamble 20%
bot: Rolled 84. pirak__ won 418 points and now has a total of 2508.
me: !gamble 300
bot: Rolled 49. pirak__ lost 300 points and now has a total of 2208.
me: !gamble all
bot: Rolled 3. pirak__ lost 2208 points and now has a total of 0.
```

**Comment by DickerSauerlaender** [comment]
in my effect, there is no subcommand with %, maybe because i just "updated" to the latest script-version. Maybe there is my problem?
Can you send me over how the subcommand is written with % usage?

Thank you in advance for your help!

**Comment by pirak** [comment]
I set it up from scratch again. My setup now looks exactly like the three images in the readme https://github.com/pirak/firebot-gambling-script#setup.

The actual `!gamble [anything]` subcommand has indeed the required additional arg count of 0, then the script handles the conversion of `!gamble` parameters `all`/`x%` into the actual number of points `n` internally.

**Comment by DickerSauerlaender** [comment]
Thanks @pirak i also started by zero now and it works fine! =)
