### ISSUE TITLE
Not able to edit script options

### ISSUE THREAD

**Issue by EpistemicPolymath** [pirak/firebot-gambling-script#92]
**Important Information**
* Script Version: Firebot Gambling Script 1.0.0 ?
* Firebot Version:  v5.48.2 ?

**Describe the bug**
I add the script and there are no script options for me to set at all:
![image](https://user-images.githubusercontent.com/16484276/145685357-8404c56e-4472-467d-8617-d50780f59b3f.png)

**To Reproduce**
Steps to reproduce the behaviour:
3. Enter command '...'

**Expected behaviour**
I am expecting to be able to edit and customize settings here. either that, or I am not understanding how to set this up. Maybe a better explanation in the documentation?

**Additional context**
Add any other context about the problem here that could be helpful.

**Comment by pirak** [comment]
Thanks, when adding the script to the bot there shouldn’t be any options. You can select the options for the script when adding the ‘Custom Gambling’ effect to a command.

I haven’t been keeping up with Firebot development lately, so the screenshots in the Readme might not be perfectly accurate any more in some places. If you have got any issues setting it up, feel free to ask in here.

**Comment by EpistemicPolymath** [comment]
Thank you for the follow-up. I hope you keep developing for FireBot. It is an incredibly good platform and I am hoping to bring more people to it. I will definitely show them this gambling script as well once I get it figured out.
